[package]
name = "armrest-editor"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "3.1.13"
rusttype = "0.8.2"
once_cell = "1.10.0"
uuid = { version = "0.8.2", features = ["v4"] }
serde = "1.0.136"
serde_json = "1.0.78"
xdg = "2.4.1"

armrest = { path = "../armrest", default-features = false }
libremarkable = { git = "https://github.com/canselcik/libremarkable", default-features = false, features = ['framebuffer'] }
#libremarkable = { path = "../libremarkable" }
